name: CI
on:
  # push:
  #   branches-ignore:
  #     - master
  #     - main
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and run tests
        run: yarn install --frozen-lockfile --silent --ignore-engines --update-checksums --non-interactive

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run: yarn test

      # add your build task

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: true # optional (default = false)
